Develop
Mmmams/bird-quiz pull request #2
Opened 2021-04-05 08:09 UTC by Mmmams

I want to merge master with develop, for the master branch has the newest features and fixed bugs.

2021-04-05 09:40 UTC, slolkunchik requested changes
your saga code is too repetitive (don't repeat yourself), apply my comments for all sagas and move libraries to the top of the module

2021-04-05 09:40 UTC, slolkunchik commented on src/components/list/list.component.jsx
> -import React, { createRef } from "react";
prioritize libraries first, then your local files

2021-04-05 09:40 UTC, slolkunchik commented on src/components/list/list.component.jsx
>  import { useDispatch, useSelector } from "react-redux";
should be near react

2021-04-05 09:40 UTC, slolkunchik commented on src/components/list/list.component.jsx
> +import { useEffect } from "react";
move it to line 1

2021-04-05 09:40 UTC, slolkunchik commented on src/components/qustion/question.component.jsx
> +  if (answered === true) {
empty line above

2021-04-05 09:40 UTC, slolkunchik commented on src/redux/birds/birds.sagas.js
> +          `https://www.flickr.com/services/rest/?method=flickr.photos.search&api_key=7ecd0010d836ddcdfb59aa1364622ed5&tag_mode=all&extras=url_m&format=json&nojsoncallback=1&tags=свиристель`
don't repeat yourself: 
- use constants for the first part of the URL, 
- add function for yield fetch (the code is repetitive)
- API key uses from env file (you need dotenv library)

2021-04-05 09:40 UTC, slolkunchik commented on src/redux/birds/birds.sagas.js
> +          `https://www.flickr.com/services/rest/?method=flickr.photos.search&api_key=7ecd0010d836ddcdfb59aa1364622ed5&tag_mode=all&extras=url_m&format=json&nojsoncallback=1&tags=иволга`
and here

2021-04-05 09:56 UTC, slolkunchik reviewed
1) update readme file - it is not about your project now
2) I suggest using airbnb eslint
3) add material Ui 
4) birdsAudio and birdsNames move to separate file with data
5) add an empty line before 'return'

2021-04-15 08:30 UTC, closed without merging

2021-04-15 08:31 UTC, Mmmams commented
close pull req bcs update my branch